/* Auto-generated by ppu_lifter.py -- do not edit by hand. */
#include "ppu_recomp.h"
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

/* MSVC compatibility helpers */
#ifdef _MSC_VER
#include <intrin.h>
/* clang-cl defines _MSC_VER but provides __builtin_clz/clzll natively, so
 * redefining them is a hard error there -- only polyfill for real MSVC. */
#ifndef __clang__
static inline int __builtin_clz(unsigned int x) {
    unsigned long idx;
    _BitScanReverse(&idx, x);
    return 31 - (int)idx;
}
static inline int __builtin_clzll(unsigned long long x) {
    unsigned long idx;
    _BitScanReverse64(&idx, x);
    return 63 - (int)idx;
}
#endif
static inline int64_t ppc_mulhd(int64_t a, int64_t b) {
    int64_t hi;
    _mul128(a, b, &hi);
    return hi;
}
static inline uint64_t ppc_mulhdu(uint64_t a, uint64_t b) {
    uint64_t hi;
    _umul128(a, b, &hi);
    return hi;
}
#else
static inline int64_t ppc_mulhd(int64_t a, int64_t b) {
    return (int64_t)((__int128)(int64_t)a * (__int128)(int64_t)b >> 64);
}
static inline uint64_t ppc_mulhdu(uint64_t a, uint64_t b) {
    return (uint64_t)((unsigned __int128)a * (unsigned __int128)b >> 64);
}
#endif

/* VM base pointer (defined by game project) */
extern "C" uint8_t* vm_base;

/* Real wall-clock PS3 timebase, 79.8 MHz (sys_timer.c) — used by mftb/mftbu. */
extern "C" uint64_t ps3_timebase_now(void);

/* Indirect call dispatch (bctrl/bctr) — implemented by the game project.
 * Looks up the guest address in CTR via a hash table and calls the
 * corresponding host function. Handles OPD resolution. */
extern "C" void ps3_indirect_call(ppu_context* ctx);

/* Trampoline function pointer for cross-fragment branches (TLS).
 * Must match the __declspec(thread) definition in indirect_dispatch. */
#if defined(_MSC_VER)
extern "C" __declspec(thread) void (*g_trampoline_fn)(void*);
#else
#if defined(__APPLE__)
extern "C" thread_local void (*g_trampoline_fn)(void*);
#else
extern "C" __thread void (*g_trampoline_fn)(void*);
#endif
#endif

/* Drain pending trampolines after any call that might set g_trampoline_fn.
 * Converts cross-fragment fallthrough chains into iterative loops. */
#define DRAIN_TRAMPOLINE(ctx) do { \
    while (g_trampoline_fn) { \
        void(*_tf)(void*) = g_trampoline_fn; \
        g_trampoline_fn = 0; \
        _tf((void*)(ctx)); \
    } \
} while(0)


/* Rotate helpers */
static inline uint32_t ppc_rlwinm(uint32_t rs, int sh, int mb, int me) {
    uint32_t rotated = (rs << sh) | (rs >> (32 - sh));
    uint32_t mask;
    if (mb <= me) {
        mask = ((uint32_t)-1 >> mb) & ((uint32_t)-1 << (31 - me));
    } else {
        mask = ((uint32_t)-1 >> mb) | ((uint32_t)-1 << (31 - me));
    }
    return rotated & mask;
}

static inline uint32_t ppc_rlwimi(uint32_t ra, uint32_t rs, int sh, int mb, int me) {
    uint32_t rotated = (rs << sh) | (rs >> (32 - sh));
    uint32_t mask;
    if (mb <= me) {
        mask = ((uint32_t)-1 >> mb) & ((uint32_t)-1 << (31 - me));
    } else {
        mask = ((uint32_t)-1 >> mb) | ((uint32_t)-1 << (31 - me));
    }
    return (rotated & mask) | (ra & ~mask);
}

/* 64-bit rotate helpers */
static inline uint64_t ppc_rotl64(uint64_t v, int n) {
    n &= 63;
    return (v << n) | (v >> (64 - n));
}
static inline uint64_t ppc_mask64(int mb, int me) {
    uint64_t mask;
    if (mb <= me) {
        mask = (mb == 0) ? ~0ULL : (~0ULL >> mb);
        mask &= (me == 63) ? ~0ULL : (~0ULL << (63 - me));
    } else {
        mask = (~0ULL >> mb) | (~0ULL << (63 - me));
    }
    return mask;
}
static inline uint64_t ppc_rldicl(uint64_t rs, int sh, int mb) {
    return ppc_rotl64(rs, sh) & ppc_mask64(mb, 63);
}
static inline uint64_t ppc_rldicr(uint64_t rs, int sh, int me) {
    return ppc_rotl64(rs, sh) & ppc_mask64(0, me);
}
static inline uint64_t ppc_rldic(uint64_t rs, int sh, int mb) {
    int me = 63 - sh;
    return ppc_rotl64(rs, sh) & ppc_mask64(mb, me);
}
static inline uint64_t ppc_rldimi(uint64_t ra, uint64_t rs, int sh, int mb) {
    int me = 63 - sh;
    uint64_t mask = ppc_mask64(mb, me);
    return (ppc_rotl64(rs, sh) & mask) | (ra & ~mask);
}

