#!/usr/bin/env python3
"""Testes de patch_host_api_decls.py -- em especial do strip_block.

Porque existe: a primeira versao do strip_block usava `.*?` com re.S; o
`.*\\n` greedy engoliu do bloco ate' ao fim do ficheiro e TRUNCOU tres chunks
do lift a 2 linhas (2026-07-26). O round-trip inject->strip==original e' o
teste que teria apanhado isso em 1 segundo.

Uso: python3 test_patch_host_api_decls.py   (rc=0 verde, rc=1 falha)
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import patch_zz_host_api_decls as P  # noqa: E402

FAILS: list[str] = []


def check(name: str, got, want) -> None:
    if got != want:
        FAILS.append(f"{name}\n    got : {got!r}\n    want: {want!r}")


def chunk(body: str) -> str:
    """Preambulo REAL do lifter: os #include vem logo depois da ancora.

    Isto nao e' cosmetico -- foi exactamente aqui que a 2a versao do
    strip_block falhou: comeu os #include do lifter por estarem colados ao
    bloco injectado.
    """
    return ('/* Auto-generated by ppu_lifter.py -- do not edit by hand. */\n'
            '#include "ppu_recomp.h"\n'
            '#include <stdio.h>\n'
            '#include <stdlib.h>\n'
            '#include <string.h>\n'
            '#include <math.h>\n' + body)


def test_roundtrip_preserva_o_ficheiro() -> None:
    """inject -> strip devolve exactamente o original (nao come o corpo)."""
    orig = chunk(
        'void func_1(PPUContext* ctx) {\n'
        '    ps3_factory_repair_vt(ctx->gpr[3]);\n'
        '}\n'
        'extern "C" void outra_coisa_qualquer(void);\n'
        'void func_2(PPUContext* ctx) { usleep(100); }\n')
    p = Path(TMP) / "rt.cpp"
    p.write_text(orig, encoding="utf-8")
    check("injectou", P.patch_one(p), 1)
    injected = p.read_text(encoding="utf-8")
    check("bloco presente", P.MARKER in injected, True)
    check("corpo intacto apos inject",
          "func_2" in injected and "usleep(100)" in injected, True)
    check("round-trip", P.strip_block(injected), orig)


def test_strip_nao_come_extern_c_do_corpo() -> None:
    """Sem bloco MARKER, strip_block e' identidade -- nao apaga nada."""
    orig = chunk('extern "C" void a(void);\nextern "C" void b(void);\nint x;\n')
    check("identidade sem marker", P.strip_block(orig), orig)


def test_strip_recorta_so_ate_ao_marcador_de_fim() -> None:
    """O bloco acaba no END_MARKER -- nada depois dele e' tocado."""
    text = (f'/* {P.MARKER}: cabecalho\n'
            ' * segunda linha do comentario */\n'
            '#include <unistd.h>\n'
            'extern "C" void a(void);\n'
            f'{P.END_MARKER}\n'
            '#include <stdio.h>\n'
            'extern "C" void b(void);\n'
            'CODIGO;\n')
    check("recorta ate' ao fim", P.strip_block(text),
          '#include <stdio.h>\nextern "C" void b(void);\nCODIGO;\n')


def test_nao_come_os_includes_do_lifter() -> None:
    """Regressao: os #include do lifter ficam colados ao bloco injectado.

    A versao heuristica do strip apagou <stdio.h>/<stdlib.h>/<string.h>/<math.h>
    dos chunks 000 e 002 e o build morreu em `undeclared identifier 'stderr'`.
    """
    orig = chunk('void f(PPUContext* c) { ps3_timebase_now(); '
                 'fprintf(stderr, "x"); }\n')
    p = Path(TMP) / "hdrs.cpp"
    p.write_text(orig, encoding="utf-8")
    P.patch_one(p)
    after = p.read_text(encoding="utf-8")
    for h in ("<stdio.h>", "<stdlib.h>", "<string.h>", "<math.h>"):
        check(f"lifter mantem {h} apos inject", h in after, True)
    P.patch_one(p)                                  # 2a passagem: o strip corre
    after2 = p.read_text(encoding="utf-8")
    for h in ("<stdio.h>", "<stdlib.h>", "<string.h>", "<math.h>"):
        check(f"lifter mantem {h} apos re-strip", h in after2, True)
    check("estavel na 2a passagem", after2, after)


def test_nao_declara_o_que_o_ficheiro_define() -> None:
    """Um chunk que DEFINE o simbolo nao leva prototipo (evita conflito)."""
    body = ('extern "C" int ps3_type15_freelist_replenish(void) {\n'
            '    return 0;\n'
            '}\n'
            'void f(void) { ps3_type15_freelist_replenish(); }\n')
    check("define -> nao declara",
          P.needed(chunk(body)), [])


def test_declara_o_que_o_ficheiro_so_chama() -> None:
    body = 'void f(PPUContext* c) { ps3_factory_repair_vt(c->gpr[3]); }\n'
    check("chama -> declara",
          P.needed(chunk(body)), ["ps3_factory_repair_vt"])


def test_chamada_dentro_de_if_nao_conta_como_definicao() -> None:
    """`if (sym(x)) {` nao pode ser confundido com uma definicao."""
    body = 'void f(PPUContext* c) { if (ps3_factory_repair_vt(c->gpr[3])) { } }\n'
    check("if(...) { nao e' definicao",
          P.defines(chunk(body), "ps3_factory_repair_vt"), False)


def test_idempotente() -> None:
    orig = chunk('void f(PPUContext* c) { ps3_timebase_now(); }\n')
    p = Path(TMP) / "idem.cpp"
    p.write_text(orig, encoding="utf-8")
    check("1a passagem", P.patch_one(p), 1)
    first = p.read_text(encoding="utf-8")
    check("2a passagem no-op", P.patch_one(p), 0)
    check("conteudo estavel", p.read_text(encoding="utf-8"), first)


def test_header_injectado_so_quando_usado() -> None:
    check("usleep -> unistd", P.needed_headers(chunk("usleep(1);\n")),
          ["#include <unistd.h>"])
    check("sem usleep -> sem header", P.needed_headers(chunk("int x;\n")), [])
    check("ja' incluido -> nao repete",
          P.needed_headers(chunk("#include <unistd.h>\nusleep(1);\n")), [])


def main() -> int:
    import tempfile
    global TMP
    with tempfile.TemporaryDirectory() as td:
        TMP = td
        for name, fn in sorted(globals().items()):
            if name.startswith("test_") and callable(fn):
                fn()
    if FAILS:
        print(f"FAIL ({len(FAILS)}):", file=sys.stderr)
        for f in FAILS:
            print("  " + f, file=sys.stderr)
        return 1
    print("[test_patch_host_api_decls] OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
